POST http://localhost:5000/users
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email" : "test1234@test.test",
  "password": "1234test",
  "isMale": true,
  "birthday" : "2000-01-01"
}